In [107]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

# Basics

In [4]:
# initializing an array
a = np.array([1,2,3]) # a 1-D array with the values 1,2,3
print(a)

[1 2 3]


In [6]:
# a 2-D array of floats. 2-D arrays are represented as a list within
# a list ([[]]) where each list is a row and each element is a column
b = np.array([[9.5,3.4,5.8],[6.9,4.2,5.1]])
print(b)

[[9.5 3.4 5.8]
 [6.9 4.2 5.1]]


In [7]:
# get the dimensions of a numpy array
print(f"Dimension for array a: {a.ndim}")
print(f"Dimension for array b: {b.ndim}")

Dimension for array a: 1
Dimension for array b: 2


In [11]:
# get the shape of an array
print("Shape: (rows,columns)")
print(f"Shape for array a: {a.shape} (since 'a' is a vector its going to only show 1 dimension)")
print(f"Shape for array b: {b.shape} ")

Shape: (rows,columns)
Shape for array a: (3,) (since 'a' is a vector its going to only show 1 dimension)
Shape for array b: (2, 3) 


In [20]:
# get the type. Even though these are small arrays they are still using 4 bytes (32bits)
# but you can change that by doing the following
a = np.array([1,2,3])
print(f"Data type before change: {a.dtype}")
print(f"Byte size before change: {a.itemsize}\n")
a = np.array([1,2,3],dtype = 'int16')
print(f"Data type after change: {a.dtype}")
print(f"Byte size after change: {a.itemsize}\n")

print(f"Each array has a length of: {a.size}")

Data type before change: int32
Byte size before change: 4

Data type after change: int16
Byte size after change: 2

Each array has a length of: 3


# 32 vs 16 bit
A 16-bit register can store 216 different values. The signed range of integer values that can be stored in 16 bits is −32,768 (−1 × 215) through 32,767 (215 − 1); the unsigned range is 0 through 65,535 (216 − 1).

A 32-bit register can store 232 different values. The range of integer values that can be stored in 32 bits depends on the integer representation used. With the two most common representations, the range is 0 through 4,294,967,295 (232 − 1) for representation as an (unsigned) binary number, and −2,147,483,648 (−231) through 2,147,483,647 (231 − 1) for representation as two's complement.

So as shown above, with 32 bit integers we can store much larger values 

In [21]:
# see how many bytes are used to store the array
a.nbytes

6

# Accessing/Changin specific elements, rows, columns, etc.

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
a.shape

(2, 7)

In [28]:
#get a specific element [r, c]. Say we want to grab a specific number like 13.
# We'd look in the 2nd row at the 6th index but since everything starts indexing
# from 0 the syntax would be as follows (just subtract 1 from the actual indexes).
print(a[1,5])
# we can also use negative notation
a[1,-2]

13


13

In [32]:
# get a specific row
print(a[0])
print(a[1])

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


In [54]:
# we can also use slice notation [start:end:step] start through not past stop, by step
row = 0
start = 0
end = 7
step = 1
a[row,start:end:step]

array([1, 2, 3, 4, 5, 6, 7])

In [58]:
# get a specific column (a[:] means return all the rows)
column = 2
a[:,2] # [get all:the rows, return the column]

array([[ 3,  4],
       [10, 11]])

In [90]:
                 ##############################################
rows = 2         # how many rows to display (2 means show all)#
columnstart = 0  # which column to start at                   #
columnend = 6    # which column to end at                     #
columnstep = 1   # how many steps to take                     #
                 ##############################################
    
a[:rows,columnstart:columnend:columnstep]

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13]])

In [92]:
# changing elements. Replace 13 with 20
print(a[1,5])
a[1,5] = 20
print(a[1,5])

13
20


In [94]:
# changing columns
print(a[:,2]) # column 2
a[:,2] = [5,15]
print(a[:,2])

[ 3 10]
[ 5 15]


# Same Examples but with 3-D arrays

In [128]:
                 # group 1        # group 2
b = np.array([   [[1,2],[3,4]] ,  [[5,6],[7,8]]   ]) # creates a 2x2x2 matrix
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [99]:
# getting specific elements. 

#In this case i want the 3 so we can see
# that 3 is in the first group, so the first index is 0. Then we see 
# that its in the second row, so the index is 1. Lastly we can see
# that it is the first element so this index is 0.
group_num = 0
row_num = 1
index_location = 0
b[group_num,row_num,index_location]

3

In [110]:
# getting specific rows
group = 0 # the group is the 2D array within the 3D array
row = 1   # the row in the 2D array that you want to access 
b[group,row]

array([3, 4])

In [190]:
# getting specific columns
groupstart = 0 # (0 == all groups, 1 == 2nd group only, 2 == no groups)
groupend = 2 # (0 == no groups, 1 == 1st group only, 2 == all groups)
rowstart = 0 # (0 == all rows, 1 == 2nd rows only, 2 == no rows)
rowend = 2 # (0 == no rows, 1 == 1st rows only, 2 == all rows)
column = 0 # (0 == column 1, 1 == column 2)

print(b[groupstart:groupend,rowstart:rowend,0])

[[1 3]
 [5 7]]


# Initializing Different types of Arrays

In [194]:
# All 0s
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [198]:
# All 1s
np.ones((10,2),dtype = 'int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [201]:
# any other number
np.full((2,2),21,dtype = 'float16')

array([[21., 21.],
       [21., 21.]], dtype=float16)

In [202]:
# full like fills an array using the shape of an array that already exists
np.full_like(a,3)

array([[3, 3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3]])

In [206]:
# random decimal numbers
np.random.rand(4,4) # the integers are the shape

array([[0.73855182, 0.60832046, 0.20392127, 0.85116187],
       [0.20223671, 0.55829521, 0.08012608, 0.348651  ],
       [0.12827197, 0.14640759, 0.32846827, 0.08155855],
       [0.62520341, 0.86921468, 0.86079722, 0.39417438]])

In [229]:
# random integer values. 
# low = lower bound (inclusive)
# high = upper bound (exclusive)
np.random.randint(low = 5,high = 15,size = (3,3))

array([[ 5,  6,  8],
       [14,  5,  6],
       [12,  5, 11]])